name: "Test"
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - shell: bash
        run: pnpm install
      - name: Install @vitest/coverage-v8
        run: pnpm add -D @vitest/coverage-v8
      - name: "Test"
        run: npx vitest run
